from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import pandas as pd
import seaborn as sns


def plot_confusion_matrix(
	csv_path: str,
	normalize: bool = False,
	title: str | None = None,
	save_path: str | None = None,
	color_scale: str = "linear",
	gamma: float = 0.5,
) -> None:
	cm_path = Path(csv_path)
	if not cm_path.exists():
		raise FileNotFoundError(f"Confusion matrix CSV not found: {cm_path}")

	cm_df = pd.read_csv(cm_path, index_col=0)
	if cm_df.empty:
		raise ValueError(f"Confusion matrix CSV is empty: {cm_path}")

	plot_df = cm_df.copy()
	if normalize:
		row_sums = plot_df.sum(axis=1).replace(0, 1)
		plot_df = plot_df.div(row_sums, axis=0)

	fig_width = max(8, int(len(plot_df.columns) * 0.9))
	fig_height = max(6, int(len(plot_df.index) * 0.8))
	plt.figure(figsize=(fig_width, fig_height))

	data_min = float(plot_df.to_numpy().min())
	data_max = float(plot_df.to_numpy().max())
	norm = None
	if color_scale == "log":
		# Log scale requires strictly positive values, so shift the lower bound.
		vmin = max(data_min, 1e-6 if normalize else 1.0)
		norm = mcolors.LogNorm(vmin=vmin, vmax=max(data_max, vmin))
	elif color_scale == "sqrt":
		norm = mcolors.PowerNorm(gamma=0.5, vmin=max(data_min, 0.0), vmax=data_max)
	elif color_scale == "power":
		if gamma <= 0:
			raise ValueError("--gamma must be > 0 when using --color-scale power")
		norm = mcolors.PowerNorm(gamma=gamma, vmin=max(data_min, 0.0), vmax=data_max)

	sns.heatmap(
		plot_df,
		annot=True,
		fmt=".2f" if normalize else "d",
		cmap="YlGnBu",
		norm=norm,
		cbar=True,
		square=True,
		linewidths=0,
		linecolor="white",
	)

	plt.title(title or ("Normalized Custom CNN Confusion Matrix (8 Breeds)" if normalize else "Custom CNN Confusion Matrix (8 Breeds)"))
	plt.xlabel("Model Predicted Label")
	plt.ylabel("True Label")
	plt.xticks(rotation=45, ha="right")
	plt.yticks(rotation=0)
	plt.tight_layout()

	if save_path:
		output_path = Path(save_path)
		output_path.parent.mkdir(parents=True, exist_ok=True)
		plt.savefig(output_path, dpi=200, bbox_inches="tight")
		print(f"Saved confusion matrix plot to: {output_path}")

	plt.show()


def main() -> None:
	parser = argparse.ArgumentParser(description="Visualize a confusion matrix from CSV.")
	parser.add_argument(
		"--csv",
		default="outputs/metrics/confusion_matrix.csv",
		help="Path to confusion matrix CSV generated by src.evaluate.",
	)
	parser.add_argument(
		"--normalize",
		action="store_true",
		help="Normalize rows to show per-class recall proportions.",
	)
	parser.add_argument("--title", default=None, help="Custom plot title.")
	parser.add_argument(
		"--save",
		default=None,
		help="Optional output image path (e.g., outputs/metrics/confusion_matrix.png).",
	)
	parser.add_argument(
		"--color-scale",
		choices=["linear", "log", "sqrt", "power"],
		default="linear",
		help="Color scaling for the heatmap to improve visibility of skewed values.",
	)
	parser.add_argument(
		"--gamma",
		type=float,
		default=0.5,
		help="Gamma value for --color-scale power (lower than 1 emphasizes smaller values).",
	)

	args = parser.parse_args()
	plot_confusion_matrix(
		csv_path=args.csv,
		normalize=args.normalize,
		title=args.title,
		save_path=args.save,
		color_scale=args.color_scale,
		gamma=args.gamma,
	)


if __name__ == "__main__":
	main()
